# Dev profile — local MySQL + Redis from Docker Compose
spring:

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 40MB   # Up to 8 files × 5MB

  # Scheduling config
  task:
    scheduling:
      pool:
        size: 2        # 2 threads for scheduled tasks
      thread-name-prefix: "turfzy-scheduler-"

  datasource:
    url: jdbc:mysql://localhost:3307/turfzy_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
    username: turfzy_user
    password: turfzy_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      pool-name: TurfzyHikariPool


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 507238275770-2j7lurulg01uo6092i6jp153h7iicpo8.apps.googleusercontent.com       # Get from Google Cloud Console
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  jpa:
    hibernate:
      ddl-auto: update    # Auto-updates schema in dev; NEVER use in prod
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

# JWT config (real secret goes in env variable in prod)
app:
  jwt:
    secret: "turfzy-dev-secret-key-change-in-production-min-256-bits-long"
    expiration-ms: 86400000       # 24 hours
    refresh-expiration-ms: 604800000  # 7 days

  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3000"

# Cloudinary — get free credentials from cloudinary.com
cloudinary:
  cloud-URL: cloudinary://327473315774365:F4Of5d9QALaFygALZmHmmEAZ__I@dxacqmgpz
  cloud-name: dxacqmgpz
  api-key: 327473315774365
  api-secret: F4Of5d9QALaFygALZmHmmEAZ__I